language: shell
script:
    - curl -L -o install-nix https://files.t-ravis.com/install-multi
    - echo "not a tty :)" | sh install-nix
    - echo "not a tty :)" | sh install-nix --uninstall

jobs:
  include:
    # test the default install across many OS/versions
    - os: osx
      osx_image: xcode8.3
    # - os: osx
    #   osx_image: xcode9
    # - os: osx
    #   osx_image: xcode9.1
    # - os: osx
    #   osx_image: xcode9.2
    # - os: osx
    #   osx_image: xcode9.3
    # - os: osx
    #   osx_image: xcode9.4
    # - os: osx
    #   osx_image: xcode10
    # - os: osx
    #   osx_image: xcode10.1
    # - os: osx
    #   osx_image: xcode11
    # - os: osx
    #   osx_image: xcode11.3
    # - os: osx
    #   osx_image: xcode11.6
    # - os: linux
    - os: osx
      osx_image: xcode12
