name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-11.0 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: ./fde.expect
      - run: fdesetup isactive
