name: "Test"
on:
  pull_request:
  push:
jobs:
  fv_enabled_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-11.0 ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: ./fde.expect
    - run: fdesetup isactive
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=https://github.com/LnL7/nixpkgs/archive/d7befcad37ed8d9e36861302c940ce6da4349311.tar.gz
        install_url: https://files.t-ravis.com/install-allowed
    - run: nix
  fv_disabled_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-11.0 ]
      fail-fast: false
    steps:
    - name: Disable syspolicy assessments
      run: |
        spctl --status
        sudo spctl --master-disable
        spctl --status || true
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=https://github.com/LnL7/nixpkgs/archive/d7befcad37ed8d9e36861302c940ce6da4349311.tar.gz
        install_url: https://files.t-ravis.com/install-allowed
    - run: nix

