name: "Test"
on:
  pull_request:
  push:
env:
  NIX_PATH: nixpkgs=https://github.com/LnL7/nixpkgs/archive/d7befcad37ed8d9e36861302c940ce6da4349311.tar.gz
jobs:
  fv_enabled_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-11.0 ]
        install_type: [ --daemon, --no-daemon ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: ./fde.expect
    - run: fdesetup isactive
    - run: |
      sh <(curl https://files.t-ravis.com/install-volume) ${{ matrix.install_type }}
      cert_file=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
      echo "NIX_SSL_CERT_FILE=$cert_file" >> $GITHUB_ENV
      export NIX_SSL_CERT_FILE=$cert_file
      sudo launchctl setenv NIX_SSL_CERT_FILE "$cert_file"
      echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> $GITHUB_PATH || true
      echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH || true
      source $HOME/.nix-profile/etc/profile.d/nix.sh || true
    - run: nix
  fv_disabled_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-11.0 ]
        install_type: [ --daemon, --no-daemon ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: |
      sh <(curl https://files.t-ravis.com/install-volume) ${{ matrix.install_type }}
      cert_file=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
      echo "NIX_SSL_CERT_FILE=$cert_file" >> $GITHUB_ENV
      export NIX_SSL_CERT_FILE=$cert_file
      sudo launchctl setenv NIX_SSL_CERT_FILE "$cert_file"
      echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> $GITHUB_PATH || true
      echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH || true
      source $HOME/.nix-profile/etc/profile.d/nix.sh || true
    - run: nix

