name: "Test"
on:
  pull_request:
  push:
env:
  NIX_PATH: nixpkgs=https://github.com/LnL7/nixpkgs/archive/d7befcad37ed8d9e36861302c940ce6da4349311.tar.gz
jobs:
  fv_enabled_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-11 ]
        install_type: [ --daemon ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: sh -c "echo nix | sudo tee -a /etc/synthetic.conf"
    - run: sh -c "if /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t; then :; fi"
    - run: sh -c "if /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B; then :; fi"
    - run: ./fde.expect
    - run: fdesetup isactive
    - run: sh <(curl -L https://releases.nixos.org/nix/nix-2.3.8/install) ${{ matrix.install_type }}
    - run: source prep.sh
    - run: nix doctor
    - name: collect sysdiagnose
      run: |
        mkdir artifacts
        sudo sysdiagnose -r artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sysdiagnose (error)
        path: artifacts
  fv_disabled_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-11 ]
        install_type: [ --daemon ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: sh <(curl -L https://releases.nixos.org/nix/nix-2.3.8/install) ${{ matrix.install_type }}
    - run: source prep.sh
    - run: nix doctor
    - name: collect sysdiagnose
      run: |
        mkdir artifacts
        sudo sysdiagnose -r artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sysdiagnose (success)
        path: artifacts

