name: "Test"
on:
  pull_request:
  push:
env:
  NIX_PATH: nixpkgs=https://github.com/LnL7/nixpkgs/archive/d7befcad37ed8d9e36861302c940ce6da4349311.tar.gz
jobs:
  nix_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-11.0 ] # ubuntu-latest,
        install_type: [ --daemon, --no-daemon ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: sh <(curl https://files.t-ravis.com/install-multi)


